resources:
  - ../../base
namespace: development

patches:
  - target:
      kind: Ingress
      name: ingress-service
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ticketing.dev.porthouse.dev
      - op: replace
        path: /spec/rules/0/host
        value: ticketing.dev.porthouse.dev
  - target:
      kind: Deployment
      name: auth-depl
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: development
