apiVersion: skaffold/v2beta28
kind: Config
deploy:
  kustomize:
    paths:
      - ./infra/k8s/overlays/production
build:
  local:
    push: true
  artifacts:
    - image: ghcr.io/anthonyporthouse/ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

profiles:
  - name: production
  - name: development
    activation:
      - command: dev
    deploy:
      kustomize:
        paths:
          - ./infra/k8s/overlays/development
